### ISSUE TITLE
Unable to get the PlugIn to work

### ISSUE THREAD

**Issue by carokiel** [AncientRoman/SublimeOpenFileOverSSH#3]
Hi,
I'm on a Mac, running Sonoma.
What I did:
- Add the repository to Package Control
- Installed the Package by Package Control
Unfortunately, the Menu item "Open via SSH" is not showing and when I klick on "Browse Packages", I can't see it, either.

Can you assist me on how to get this working?
Thank you so much,
Caroline

**Comment by AncientRoman** [comment]
Hey,
That should work.
Let me see if I can help you.

If you click on Browse Packages, go up a directory level, and then open Installed Packages, you should see a SublimeOpenFileOverSSH.sublime-package.
Also note that Open Over SSH is not a menu item, it's a command in the command pallet. Press CMD-SHFT-P and then type in Open File Over SSH.

I do like the idea of making Open via SSH a menu item under File. I'm working on an update to this package right now and I'll add the feature to the update. Thanks!

Let me know how those two things go. We'll get this working for you.

**Comment by carokiel** [comment]
Hi,
thank youu very much for the fast answer and yes, it works, as suggested.
Love the idea to get it in the menu, though.

All the best,
Caroline
