### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by ydong08** [AncientRoman/SublimeOpenFileOverSSH#4]
Very Thanks for your work on this plugin!
I download it by git, and it says error when 'Open File'.
Here is log:
```
Traceback (most recent call last):
  File "D:\SublimeText\Lib\python38\sublime_plugin.py", line 1398, in setup_
    items = self.list_items()
  File "D:\SublimeText\Data\Packages\SublimeOpenFileOverSSH\main.py", line 522, in list_items
    files = self.ssh.runCmd("/bin/ls -1Lp")
  File "D:\SublimeText\Data\Packages\SublimeOpenFileOverSSH\main.py", line 166, in runCmd
    self.shell.stdin.flush()
OSError: [Errno 22] Invalid argument
reloading settings Packages/User/SublimeOpenFileOverSSH.sublime-settings
```

**Comment by AncientRoman** [comment]
Hmmm it looks like your ssh connection is dropping or closing prematurely. OSError 22 on a windows system can also mean errorno 32 which is a broken pipe. I'm guessing that's what this is, but I'm not sure.
Let's see if we can figure this out.
Can you successfully ssh into your server from the command line?
Does this error happen every time even with a different server?

This pipe closed error may be related to ssh's Multiplexing feature. Now that I think about it, Windows might not support the Unix sockets required for that feature to work. Try disabling multiplexing in the settings file and see if that fixes the problem.

**Comment by ydong08** [comment]
You are right. When DISABLE Multiplexing feature, it works well now. Thanks!

**Comment by AncientRoman** [comment]
Wonderful! Thank you for trying that.
I will look into this more and update the package with a fix. In the meantime just keep multiplexing disabled.
Thanks for opening this Issue. Have a good one!
