### ISSUE TITLE
[feature] Remember the last selected path

### ISSUE THREAD

**Issue by ydong08** [AncientRoman/SublimeOpenFileOverSSH#8]
Can an entry be added here to indicate the last selected path ? That will help to achieve faster file navigation.
![last_path](https://github.com/user-attachments/assets/41c8c0f9-0424-40a4-ac77-b8f8cdd9a700)

**Comment by AncientRoman** [comment]
The default selection in the file browser should be the last selected/opened path.
If it's not, let me know and I'll fix it.
Having the last opened path be the default selection was the fastest way I could think of to reopen or reenter the same file/folders.

**Comment by ydong08** [comment]
Yeah, it focuses on last selected/opened path per level, which is an efficient way. 
However, if a project has many directory levels, it's another time-saving way that focus the last selected full path at the first moment.
for example, it focuses `/home/github` directory, and also shows the last selected full path, such as  `/home/github/branch/project/product/module/source`.

**Comment by AncientRoman** [comment]
Alright yeah, I feel you. I'll add that with a setting to control its visibility.
Until then, you can set a project directory of sorts by typing the path in the server input like: `user@server.ext:github/branch/project/product/`
Thanks!

**Comment by AncientRoman** [comment]
I added a Last Dir action which you can enable by setting the `"lastDirAction"` setting to `true`.
I will continue to tweak it, but let me know what you think and if it's what you were looking for 👍

**Comment by ydong08** [comment]
Yeah, that is all what i want. I try it just now, it works well.

**Comment by AncientRoman** [comment]
Sweeeet. Appreciate the feedback.

**Comment by AncientRoman** [comment]
I've finished my updates to actions and Last Dir.
Available actions are now controlled with the `"actions"` setting.
To enable Last Dir you'd want something like this: `"actions": ["glob", "new", "lastDir"]`.

Have good one!
